spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/jobrunr-example}
    username: ${DB_USER:}
    password: ${DB_PASS:}
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8000
